Build with gnutls:
  script:
  - git submodule update --init && autoreconf -fvi && 
    ./configure && make -j4 && make check VERBOSE=1 -j4
  tags:
  - gnutls3.3
  - ocserv
  except:
  - tags

Build with openssl and gnutls:
  script:
  - git submodule update --init && autoreconf -fvi && 
    ./configure --without-openssl-version-check --enable-dtls-xfail --with-openssl &&
    make -j4 && make check VERBOSE=1 -j4
  tags:
  - gnutls3.3
  - openssl
  - ocserv
  except:
  - tags

Build with openssl:
  script:
  - git submodule update --init && autoreconf -fvi && 
    ./configure --without-gnutls --with-openssl --without-openssl-version-check --enable-dtls-xfail &&
    make -j4 && make check VERBOSE=1 -j4
  tags:
  - openssl
  - ocserv
  except:
  - tags

Build and Check for windows:
  script:
  - git submodule update --init && autoreconf -fvi && 
    mingw32-configure && mingw32-make -j4 &&
    mingw32-make -j4 check VERBOSE=1
  tags:
  - gnutls3.3
  - wine
  - mingw
  except:
  - tags

Build and Check for FreeBSD:
  script:
  - git submodule update --init && autoreconf -fvi &&
    ./configure && make -j4 && make check VERBOSE=1 -j4
  tags:
  - freebsd
  except:
  - tags
