notifications:
  email:
    false

dist: trusty
sudo: false

language: c
compiler:
  - gcc

env:
  global:
    - MAKEFLAGS="-j 2"

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential autoconf automake libtool pkg-config
                 vpnc-scripts
                 gettext libproxy-dev libxml2-dev liblz4-1 liblz4-dev libstoken-dev liboath-dev
                 libgnutls28-dev # actually GnuTLS 3.2.11 ¯\_(ツ)_/¯


script: ./autogen.sh &&
        ./configure &&
        make VERBOSE=1 version.c &&
        make &&
        make VERBOSE=1 -j4 check

jobs:
  include:
    - stage: docker build
      sudo: required
      services:
        - docker
      before_install:
        - docker build -t openconnect .
      script:
        - docker run openconnect "/openconnect/openconnect" "-V"
